server:
  port: 8080
  servlet:
    context-path: /api

spring:
  config:
    import: optional:file:.env[.properties]
  application:
  name: articles
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_ROOT_PASSWORD}
    url: "jdbc:postgresql://localhost:5433/articles"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}